version: '3.7'

services:
  # database
  # database_category_apple_supermarket:
  #   image: postgres
  #   container_name: msSupermarketCategoryDb
  #   restart: always
  #   ports: 
  #     - 5438:5432
  #   environment:
  #     - POSTGRES_USER=${DB_USERNAME}
  #     - POSTGRES_PASSWORD=${DB_PASSWORD}
  #     - POSTGRES_DB=${DB_NAME}
  #   volumes:
  #     - pgdata:/data/postgres
  #   networks:
  #     - kong-net
    # network_mode: host

  # API
  app:
    build: .
    container_name: category-microservice-gas
    ports:
      - 8004:8004
    volumes:
      - .:/usr/app
    command: sh -c "npm run typeorm migration:run && npm run dev"
       
    # network_mode: host
    # depends_on: 
    #   - database_category_apple_supermarket
    # networks:
    #   - kong-net
      
# volumes:
#   pgdata: 

# networks:
#   kong-net:
#     external: true