version: '3.7'

services: 
  database_category_apple_supermarket:
    image: postgres
    container_name: msSupermarketCategoryDb
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - pgdata:/data/postgres
    network_mode: host


volumes:
  pgdata: